// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ItemsController from "./items_controller"
application.register("items", ItemsController)

import NotesController from "./notes_controller"
application.register("notes", NotesController)

import NotificationSubscriptionController from "./notification_subscription_controller"
application.register("notification-subscription", NotificationSubscriptionController)
