development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 28045636724-fs7b9s1qj0m3ui9b7rqdi0vb4ndkbikt.apps.googleusercontent.com
  google_client_secret: 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
